/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package banaonam.view;

import banaonam.model.hoadon;
import banaonam.model.khachhang;
import banaonam.model.hoadonchitiet;
import banaonam.model.sanphamchitiet;
import banaonam.sevice.ChatLieuService;
import banaonam.sevice.hoadonchitietservice;
import banaonam.sevice.hoadonservice;
import banaonam.sevice.khachhangservice;
import banaonam.sevice.mauService;
import banaonam.sevice.nhanvienservice;
import banaonam.sevice.sanphamchitietService;
import banaonam.sevice.sanphamservice;
import banaonam.sevice.sizeService;
import banaonam.sevice.taikhoanservice;
import static banaonam.view.DangNhapJFrame.txtUser;
import java.text.Normalizer;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class manhinhhoadon extends javax.swing.JInternalFrame {

    /**
     * Creates new form manhinhhoadon
     */
    sanphamchitietService serviceSPCT = new sanphamchitietService();
    hoadonservice serviceHD = new hoadonservice();
    taikhoanservice serviceTK = new taikhoanservice();
    nhanvienservice serviceNV = new nhanvienservice();
    hoadonchitietservice serviceHDCT = new hoadonchitietservice();
    sanphamservice serviceSP = new sanphamservice();
    khachhangservice serviceKH = new khachhangservice();

    List<sanphamchitiet> listGioHang = new ArrayList<>();
    int index;
    double tongTien = 0;
    int soPage = serviceSPCT.getCount();
    int page = 1;

    public manhinhhoadon() {
        initComponents();

        setlaiborder();
        if (soPage / 3 != 0) {
            soPage++;
        }

        fillTableSP(serviceSPCT.getallsanphamchitiet());

        fillHoaDon(serviceHD.getAllHD());
        lblMaNV.setText(serviceTK.getMaTK(txtUser.getText()) + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDOn = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        lblMaNV = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnThanhToan = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiemSanPham = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cbxTimKiem = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        tblHoaDOn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã HD", "Mã NV", "Trạng thái", "Ngày tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDOnMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHoaDOn);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Màu sắc", "Chất liệu", "Size", "Giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma HDCT", "Mã SP", "Tên SP", "Số lượng", "Giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGioHang);

        jToggleButton3.setText("Xóa");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Sửa");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton2))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jToggleButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToggleButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jToggleButton1.setText("Tạo hóa đơn");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        lblMaNV.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã HD");

        txtMaHD.setEditable(false);
        txtMaHD.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tên khách hàng");

        txtTenKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Tên nhân viên");

        txttenNV.setEditable(false);
        txttenNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Ngày tạo");

        txtNgayTao.setEditable(false);
        txtNgayTao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Tổng tiền");

        txtTongTien.setEditable(false);
        txtTongTien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Tiền khách đưa");

        txtTienKhachDua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTienKhachDua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTienKhachDuaMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Tiền thừa");

        txtTienThua.setEditable(false);
        txtTienThua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Số điện thoại");

        txtSDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSDTMouseClicked(evt);
            }
        });
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(46, 46, 46)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThanhToan)
                .addGap(88, 88, 88))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnThanhToan)
                .addGap(16, 16, 16))
        );

        jToggleButton4.setText("jToggleButton4");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("tìm kiếm");

        jButton1.setText("tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbxTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mã sản phẩm", "tên sản phẩm" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("tìm kiếm");

        jButton2.setText("trở lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 12, Short.MAX_VALUE)
                                .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(415, 415, 415)
                    .addComponent(jLabel9)
                    .addContainerGap(415, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton4))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(cbxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(jLabel9)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        if (!txtMaHD.getText().isEmpty()) {
            int nhapSL = Integer.parseInt(JOptionPane.showInputDialog("Mời nhập số lượng"));
            boolean check = false;
            index = tblSanPham.getSelectedRow();

            sanphamchitiet spct = serviceSPCT.getallsanphamchitiet().get(index);
            int soluong = spct.getSOLUONG();

            // Thêm số lượng, check và fill lên
            if (nhapSL <= soluong && nhapSL > 0) {

                hoadonchitiet hdct = new hoadonchitiet();
                int maSPCT = serviceSPCT.getMaSPCT(spct.getMau(), spct.getChatlieu(), spct.getSIZE(),
                        spct.getMASP());
                int maHD = Integer.parseInt(txtMaHD.getText());
                double tongTienSP = spct.getThanhTien(spct.getGIA(), nhapSL);
                int soLuong = nhapSL;

                hdct.setMaCTSP(maSPCT);
                //System.out.println("" + maSPCT);
                //System.out.println("" + serviceSPCT.getMaSP(maSPCT));

                hdct.setMaHD(maHD);
                hdct.setTongTien(tongTienSP);
                hdct.setSoLuong(soLuong);
                // System.out.println("" + soLuong);
                hdct.setTrangThai("Chưa thanh toán");

                if (serviceHDCT.checkTrungCTSP(maHD, maSPCT) != null) {
                    hoadonchitiet hdct1 = serviceHDCT.checkTrungCTSP(maHD, maSPCT);
                    serviceHDCT.upfateSL(hdct1, hdct1.getSoLuong() + nhapSL);
                    fillTableGioHang(serviceHDCT.getHDByMAHD(maHD));
                    serviceSPCT.updateSL(maSPCT, soluong - nhapSL);
                    System.out.println(" check 1");
                    System.out.println(" " + hdct1.getMaHDCT());
                    serviceSPCT.updateSL(maSPCT, soluong - nhapSL);
                    fillTableSP(serviceSPCT.getallsanphamchitiet());

                } else {
                    if (serviceHDCT.addHDCT(hdct) != 0) {
                        if (serviceHDCT.getHDByMAHD(maHD).size() > 0) {
                        }
                        fillTableGioHang(serviceHDCT.getHDByMAHD(maHD));
                        serviceSPCT.updateSL(maSPCT, soluong - nhapSL);
                        fillTableSP(serviceSPCT.getallsanphamchitiet());

                    }
                }

                // Thêm sản phẩm vào hóa đơn chi tiết
                /*for (sanphamchitiet x : listGioHang) {
                hoadonchitiet hdct = new hoadonchitiet();
                int maSPCT = serviceSPCT.getMaSPCT(x.getMau(), x.getChatlieu(), x.getSIZE(), x.getMASP());
                int maHD = Integer.parseInt(txtMaHD.getText());
                double tongTienSP = x.getThanhTien(x.getGIA(), x.getSOLUONG());
                int soLuong = x.getSOLUONG();

                hdct.setMaCTSP(maSPCT);
                System.out.println("" + maSPCT);
                hdct.setMaHD(maHD);
                hdct.setTongTien(tongTienSP);
                hdct.setSoLuong(soLuong);
                System.out.println("" + soLuong);
                hdct.setTrangThai("Chưa thanh toán");
                hdct.setGia(Double.valueOf(x.getGIA()));
                serviceHDCT.addHDCT(hdct);
                int soLuongGoc = serviceSPCT.getSLSPCT(maSPCT);
                serviceSPCT.updateSL(maSPCT, soLuongGoc - soLuong);
                System.out.println("" + maSPCT);
                System.out.println("" + soLuongGoc);
                System.out.println("" + soLuong);
            } */
                // Tinh tien
                if (serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText())).size() > 0) {
                    for (hoadonchitiet x : serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText()))) {
                        tongTien += x.getThanhTien(x.getGia(), x.getSoLuong());

                    }
                    txtTongTien.setText("" + tongTien);
                    tongTien = 0;
                } else {
                    txtTongTien.setText("" + 0);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn");
        }


    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        // Tạo 1 hóa đơn rỗng
        hoadon hd = new hoadon();
        DangNhapJFrame dangNhap = new DangNhapJFrame();

        int maTK = Integer.parseInt(lblMaNV.getText());
        int maNV = serviceNV.getMaNV(maTK);
        LocalDate now = LocalDate.now();
        String ngay = now.toString();
        String trangThai = "Chờ thanh toán";
        int maKH = 1;

        // THêm  các dữ liệu vào hóa đơn
        hd.setMaKH(maKH);
        System.out.println("" + maKH);
        hd.setMaNV(maNV);
        System.out.println("" + maNV);
        hd.setNgayTao(ngay);
        System.out.println("" + ngay);
        hd.setTrangThai(trangThai);
        System.out.println("" + trangThai);

        if (serviceHD.getAllHD().size() < 10) {
            if (serviceHD.addHD(hd) != 0) {
                fillHoaDon(serviceHD.getAllHD());
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        if (checkFormHD()) {
            if (serviceKH.getBySDT(txtSDT.getText()) == null) {
                JOptionPane.showMessageDialog(this, "Khách hàng chưa tồn tại, hãy thêm khách hàng");

            } else {
                JOptionPane.showMessageDialog(this, "Thanh toán thành công");
                for (hoadonchitiet x : serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText()))) {
                    serviceHDCT.updateTrangThai(x, "Đã thanh toán");
                }

                serviceHD.updateHD(serviceKH.getMaKH(txtSDT.getText()), Integer.parseInt(txtMaHD.getText()));
                txtNgayTao.setText("");
                txtMaHD.setText("");
                txtTienKhachDua.setText("");
                txtTienThua.setText("");
                txttenNV.setText("");
                txtTongTien.setText("");
                txtTenKH.setText("");
                txtSDT.setText("");

                System.out.println("" + serviceKH.getMaKH(txtSDT.getText()));
                fillTableGioHang(serviceHDCT.getHDByMAHD(0));
                fillHoaDon(serviceHD.getAllHD());

            }
        }


    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void tblHoaDOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDOnMouseClicked
        // TODO add your handling code here:
        index = tblHoaDOn.getSelectedRow();
        hoadon hd = serviceHD.getAllHD().get(index);

        txtMaHD.setText(hd.getMaHD() + "");
        txtNgayTao.setText(hd.getNgayTao());
        txttenNV.setText(serviceNV.tenNV(hd.getMaNV()));
        fillTableGioHang(serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText())));

        if (serviceHDCT.getHDByMAHD(hd.getMaHD()).size() > 0) {
            for (hoadonchitiet x : serviceHDCT.getHDByMAHD(hd.getMaHD())) {
                tongTien += x.getThanhTien(x.getGia(), x.getSoLuong());

            }
            txtTongTien.setText("" + tongTien);
            tongTien = 0;
        } else {
            txtTongTien.setText("" + 0);
        }

    }//GEN-LAST:event_tblHoaDOnMouseClicked

    private void txtTienKhachDuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTienKhachDuaMouseClicked
        // TODO add your handling code here:
        if (!txtTienKhachDua.getText().isEmpty()) {
            if (Double.parseDouble(txtTienKhachDua.getText()) >= Double.parseDouble(txtTongTien.getText())) {
                String tienThua = String.valueOf(Double.parseDouble(txtTienKhachDua.getText()) - Double.parseDouble(txtTongTien.getText()));
                txtTienThua.setText(tienThua);
            } else {
                JOptionPane.showMessageDialog(this, "Số tiền không đủ");
            }
        }
    }//GEN-LAST:event_txtTienKhachDuaMouseClicked

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblGioHangMouseClicked

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:

        int slSua = Integer.parseInt(JOptionPane.showInputDialog("Mời nhập số lượng").toString());
        // Vị trí click trên table Giỏ hàng
        index = tblGioHang.getSelectedRow();
        // Lấy ra hoadonchitiet đuợc click
        hoadonchitiet hdct = serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText())).get(index);

        // sanphamchitiet của hoadonchitiet trên
        sanphamchitiet spct = serviceSPCT.getMaSPCT(serviceHDCT.getMaCTSP(hdct.getMaHDCT()));

        serviceSPCT.updateSL(serviceHDCT.getMaCTSP(hdct.getMaHDCT()), (hdct.getSoLuong() + spct.getSOLUONG()) - slSua);
        serviceHDCT.upfateSL(hdct, slSua);
        fillTableSP(serviceSPCT.getallsanphamchitiet());
        fillTableGioHang(serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText())));
        tinhTien();


    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:

        // Vị trí click trên table Giỏ hàng
        index = tblGioHang.getSelectedRow();
        // Lấy ra hoadonchitiet đuợc click
        hoadonchitiet hdct = serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText())).get(index);

        // sanphamchitiet của hoadonchitiet trên
        sanphamchitiet spct = serviceSPCT.getMaSPCT(serviceHDCT.getMaCTSP(hdct.getMaHDCT()));

        // Cập nhật lại số lượng trong table sanphamchitiet
        serviceSPCT.updateSL(serviceHDCT.getMaCTSP(hdct.getMaHDCT()), spct.getSOLUONG() + hdct.getSoLuong());
        ///System.out.println(" "+serviceHDCT.getMaCTSP(hdct.getMaHDCT()));
        // Nếu xóa thành công
        if (serviceHDCT.deleteHDCT(hdct.getMaHDCT()) != 0) {
            fillTableGioHang(serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText())));
            // serviceSPCT.updateSL(serviceHDCT.getMaCTSP(hdct.getMaHDCT()), 10);
            int maHDCT = hdct.getMaHDCT();
            System.out.println("" + maHDCT);
            fillTableSP(serviceSPCT.getallsanphamchitiet());
            tinhTien();

        } else {
            JOptionPane.showMessageDialog(this, "Looix");
            /*System.out.println("" + hdct.getMaHDCT());
            System.out.println("" + hdct.getMaSP());
            System.out.println("" + hdct.getTenSP());
            System.out.println("" + hdct.getSoLuong());
            System.out.println("" + hdct.getGia()); */
        }

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtSDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTMouseClicked
        // TODO add your handling code here:
        if (!txtSDT.getText().isEmpty()) {
            String tenKH = serviceKH.getTenKH(txtSDT.getText());
            txtTenKH.setText(tenKH);
        }

    }//GEN-LAST:event_txtSDTMouseClicked

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTenKHActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        JDialog p = new JDialog();
        p.setSize(400, 400);
        p.add(new themNhanhKH());
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 if (txtTimKiemSanPham.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(this, "vui lòng nhập thông tin để tìm");
            return;
        }
        timkiemSP();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fillTableSP(serviceSPCT.getallsanphamchitiet());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnThanhToan;
    private javax.swing.JComboBox<String> cbxTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblHoaDOn;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtNgayTao;
    public static javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTimKiemSanPham;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txttenNV;
    // End of variables declaration//GEN-END:variables

    private void fillTableSP(List<sanphamchitiet> list) {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        int i = 1;
        for (sanphamchitiet x : list) {

            Object obj[] = {
                i++,
                x.getMASP(),
                x.getTensp(),
                x.getSIZE(),
                x.getMau(),
                x.getChatlieu(),
                x.getGIA(),
                x.getSOLUONG(),};
            model.addRow(obj);

        }

    }

    private void fillTableGioHang(List<hoadonchitiet> list) {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblGioHang.getModel();
        model.setRowCount(0);
        for (hoadonchitiet x : list) {
            model.addRow(new Object[]{x.getMaHDCT(), x.getMaSP(),
                x.getTenSP(),
                x.getSoLuong(),
                x.getGia(),
                x.getThanhTien(x.getGia(), x.getSoLuong())});
        }
    }

    private void fillHoaDon(List<hoadon> list) {
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblHoaDOn.getModel();
        model.setRowCount(0);
        int i = 1;
        for (hoadon x : list) {
            model.addRow(new Object[]{
                i++, x.getMaHD(), serviceNV.tenNV(x.getMaNV()), x.getTrangThai(), x.getNgayTao()});
        }

    }

    private boolean checkFormHD() {
        if (txtMaHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có hóa đơn cho thanh toán này");
            return false;
        }
        if (txtSDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có khách hàng cho thanh toán này");
            txtSDT.requestFocus();
            return false;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tiền khách đưa");
            txtTienKhachDua.requestFocus();
            return false;
        }
        try {
            Double.parseDouble(txtTienKhachDua.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tiền phải là số");
            txtTienKhachDua.requestFocus();
            return false;
        }
        if (txtTienThua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hệ thống đang tính, vui lòng chờ");
            txtTienKhachDua.requestFocus();
            return false;
        }

        return true;

    }

    private void tinhTien() {
        if (serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText())).size() > 0) {
            for (hoadonchitiet x : serviceHDCT.getHDByMAHD(Integer.parseInt(txtMaHD.getText()))) {
                tongTien += x.getThanhTien(x.getGia(), x.getSoLuong());

            }
            txtTongTien.setText("" + tongTien);
            tongTien = 0;
        } else {
            txtTongTien.setText("" + 0);
        }
    }

    private void setlaiborder() {
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        setSize(900, 460);
    }

    
        public void timkiemSP() {
        sanphamchitietService spct = new sanphamchitietService();
        if (cbxTimKiem.getSelectedIndex() == 0) {
            DefaultTableModel dtm = (DefaultTableModel) tblSanPham.getModel();
            dtm.setRowCount(0);
            int i = 1;
            for (sanphamchitiet object : spct.getallsanphamchitiet()) {
                if (txtTimKiemSanPham.getText().equalsIgnoreCase(object.getMASP())) {
                    Object[] obj = {
                        i++,
                        object.getMASP(),
                        object.getTensp(),
                        object.getMau(),
                        object.getChatlieu(),
                        object.getSIZE(),
                        object.getGIA(),
                        object.getSOLUONG(),};
                    dtm.addRow(obj);
                }
            }
        } else {
            DefaultTableModel dtm = (DefaultTableModel) tblSanPham.getModel();
            dtm.setRowCount(0);
            int i = 1;
            for (sanphamchitiet object : spct.getallsanphamchitiet()) {
                String ten = object.getTensp();
                String normalized = Normalizer.normalize(ten, Normalizer.Form.NFD);
                Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
                String output = pattern.matcher(normalized).replaceAll("");
                System.out.print(ten);
                if (txtTimKiemSanPham.getText().equalsIgnoreCase(output)) {
                    Object[] obj = {
                        i++,
                        object.getMASP(),
                        object.getTensp(),
                        object.getMau(),
                        object.getChatlieu(),
                        object.getSIZE(),
                        object.getGIA(),
                        object.getSOLUONG(),};
                    dtm.addRow(obj);
                }
            }
        }
    }
    
}
